# Generated by Django 6.0.3 on 2026-07-14 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(db_index=True, max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=40)),
                ('user_agent', models.CharField(blank=True, max_length=300)),
                ('referrer', models.CharField(blank=True, max_length=300)),
                ('is_authenticated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at', 'session_key'], name='main_pagevi_created_17ddf9_idx')],
            },
        ),
    ]
