# Generated by Django 6.0.3 on 2026-07-15 03:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_pagevisit'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='phone',
            field=models.CharField(default='', max_length=20, validators=[django.core.validators.RegexValidator(message="Telefon raqamini to'g'ri kiriting. Masalan: +998901234567", regex='^\\+?[0-9\\s\\-()]{7,20}$')]),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
