# Generated by Django 6.0.3 on 2026-07-20 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_blockedip'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagevisit',
            name='is_bot',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='pagevisit',
            name='status_code',
            field=models.PositiveSmallIntegerField(db_index=True, default=200),
        ),
        migrations.CreateModel(
            name='VisitorSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=40, unique=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, db_index=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('browser', models.CharField(blank=True, db_index=True, max_length=60)),
                ('browser_version', models.CharField(blank=True, max_length=30)),
                ('os', models.CharField(blank=True, db_index=True, max_length=60)),
                ('os_version', models.CharField(blank=True, max_length=30)),
                ('device_type', models.CharField(blank=True, choices=[('mobile', 'Telefon'), ('tablet', 'Planshet'), ('desktop', 'Kompyuter'), ('bot', 'Bot'), ('other', 'Boshqa')], db_index=True, max_length=20)),
                ('device_model', models.CharField(blank=True, max_length=80)),
                ('language', models.CharField(blank=True, max_length=20)),
                ('timezone', models.CharField(blank=True, max_length=60)),
                ('is_bot', models.BooleanField(db_index=True, default=False)),
                ('bot_name', models.CharField(blank=True, max_length=60)),
                ('referer', models.TextField(blank=True)),
                ('referer_source', models.CharField(blank=True, db_index=True, max_length=40)),
                ('landing_page', models.CharField(blank=True, max_length=255)),
                ('exit_page', models.CharField(blank=True, max_length=255)),
                ('page_count', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('last_activity', models.DateTimeField(auto_now=True, db_index=True)),
                ('country', models.CharField(blank=True, db_index=True, max_length=60)),
                ('country_code', models.CharField(blank=True, max_length=2)),
                ('region', models.CharField(blank=True, max_length=80)),
                ('city', models.CharField(blank=True, max_length=80)),
                ('isp', models.CharField(blank=True, max_length=120)),
                ('asn', models.CharField(blank=True, max_length=40)),
            ],
            options={
                'ordering': ['-last_activity'],
                'indexes': [models.Index(fields=['-last_activity', 'is_bot'], name='main_visito_last_ac_16365d_idx'), models.Index(fields=['started_at', 'is_bot'], name='main_visito_started_feb9ed_idx')],
            },
        ),
        migrations.AddField(
            model_name='pagevisit',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='main.visitorsession'),
        ),
        migrations.AddIndex(
            model_name='pagevisit',
            index=models.Index(fields=['created_at', 'is_bot'], name='main_pagevi_created_828096_idx'),
        ),
        migrations.AddIndex(
            model_name='pagevisit',
            index=models.Index(fields=['status_code', 'created_at'], name='main_pagevi_status__54d700_idx'),
        ),
    ]
